import {json} from '../../lib/auth.js';
import {markOrderPaid,processedEvent,cancelOrderEntitlementIfCurrent,basicAuth} from '../../lib/payments.js';
async function token(env){const base=env.PAYPAL_ENV==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';const r=await fetch(base+'/v1/oauth2/token',{method:'POST',headers:{authorization:basicAuth(env.PAYPAL_CLIENT_ID,env.PAYPAL_CLIENT_SECRET),'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!r.ok)throw new Error('auth');const j=await r.json();return {base,token:j.access_token}}
async function verify(ctx,event){if(!ctx.env.PAYPAL_WEBHOOK_ID)return false;const pp=await token(ctx.env);const h=ctx.request.headers;const payload={auth_algo:h.get('paypal-auth-algo'),cert_url:h.get('paypal-cert-url'),transmission_id:h.get('paypal-transmission-id'),transmission_sig:h.get('paypal-transmission-sig'),transmission_time:h.get('paypal-transmission-time'),webhook_id:ctx.env.PAYPAL_WEBHOOK_ID,webhook_event:event};const r=await fetch(pp.base+'/v1/notifications/verify-webhook-signature',{method:'POST',headers:{authorization:'Bearer '+pp.token,'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)return false;const j=await r.json();return j.verification_status==='SUCCESS'}
function orderIdFor(event){return String(event?.resource?.custom_id||event?.resource?.purchase_units?.[0]?.custom_id||event?.resource?.supplementary_data?.related_ids?.order_id||'')}
export async function onRequestPost(ctx){
  try{const event=await ctx.request.json();const eventId=String(event?.id||'');if(eventId&&await processedEvent(ctx,'paypal',eventId))return json({ok:true,duplicate:true});if(!(await verify(ctx,event)))return json({ok:false,error:'invalid_signature'},401);
    const type=String(event.event_type||'');let orderId=orderIdFor(event),subscriptionId=String(event?.resource?.id||'');
    if(!orderId&&subscriptionId){const o=await ctx.env.DB.prepare('SELECT id FROM orders WHERE provider=? AND subscription_id=?').bind('paypal',subscriptionId).first();orderId=o?.id||''}
    if(!orderId&&event?.resource?.supplementary_data?.related_ids?.order_id){const providerOrder=String(event.resource.supplementary_data.related_ids.order_id);const o=await ctx.env.DB.prepare('SELECT id FROM orders WHERE provider=? AND provider_checkout_id=?').bind('paypal',providerOrder).first();orderId=o?.id||''}
    if(!orderId)return json({ok:true,ignored:true});const order=await ctx.env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(orderId).first();if(!order)return json({ok:true,ignored:true});
    if(type==='PAYMENT.CAPTURE.COMPLETED'||type==='BILLING.SUBSCRIPTION.ACTIVATED'||type==='PAYMENT.SALE.COMPLETED'){
      const val=Number(event?.resource?.amount?.value||event?.resource?.amount_with_breakdown?.gross_amount?.value||order.expected_amount_usd);if(type==='PAYMENT.CAPTURE.COMPLETED'&&Math.abs(val-Number(order.expected_amount_usd))>0.01)return json({ok:false,error:'amount_mismatch'},400);await markOrderPaid(ctx,orderId,{providerPaymentId:String(event?.resource?.id||eventId),subscriptionId:order.billing_type==='subscription'?subscriptionId:null,amountPaid:val,currency:event?.resource?.amount?.currency_code||'USD',eventId});
    } else if(['BILLING.SUBSCRIPTION.CANCELLED','BILLING.SUBSCRIPTION.EXPIRED','BILLING.SUBSCRIPTION.SUSPENDED','BILLING.SUBSCRIPTION.PAYMENT.FAILED','PAYMENT.CAPTURE.DENIED','PAYMENT.SALE.REFUNDED','PAYMENT.SALE.REVERSED'].includes(type)){
      const st=type.includes('PAYMENT.FAILED')?'past_due':type.includes('REFUND')||type.includes('REVERSED')?'cancelled':type.includes('SUSPENDED')?'past_due':'cancelled';await ctx.env.DB.prepare('UPDATE orders SET status=?,updated_at=? WHERE id=?').bind(st,Date.now(),orderId).run();await cancelOrderEntitlementIfCurrent(ctx,order,{status:st,subscriptionId:order.subscription_id||subscriptionId||null});if(eventId)await ctx.env.DB.prepare('INSERT OR IGNORE INTO processed_webhooks(provider,event_id,order_id,processed_at) VALUES (?,?,?,?)').bind('paypal',eventId,orderId,Date.now()).run();
    }
    return json({ok:true});
  }catch(e){console.error(e);return json({ok:false,error:'server_error'},500)}
}
